{
 "title": "UAS Cloud Observability Dashboard",
 "tags": [
  "UAS",
  "Cloud"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# UAS Cloud Observability Dashboard\nReal-time monitoring of CSV Analytics App"
   }
  },
  {
   "title": "Total Files Uploaded",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_csv_upload_total)" }
   ]
  },
  {
   "title": "Total Rows Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_csv_rows_processed_total)"
    }
   ]
  },
  {
   "title": "Last Batch Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_last_batch_revenue_total" }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_logic_errors_total)" }
   ]
  },
  {
   "title": "Processing Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(app_csv_rows_processed_total[1m])",
     "legendFormat": "Rows/sec"
    }
   ]
  },
  {
   "title": "Average Processing Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "app_csv_processing_seconds_sum / app_csv_processing_seconds_count",
     "legendFormat": "Avg Latency"
    }
   ]
  },
  {
   "title": "System CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"uas_.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}